version: '2'
services:
    node:
        build: ./node
        image: log84.de/node
        command: /bin/true
        
    server:
        container_name: log84-server
        build: ./server
        env_file: 
            - ./server/env.properties
        expose: 
            - "1337"
        ports:
            - "1337:1337"
        links:
            - mongodb
        depends_on:
            - node
    dbdata:
        image: mongo
        volumes: 
            - /data/db
            - /data/configdb
        command: /bin/true      
            
    mongodb:
        container_name: log84-db
        image: mongo
        volumes_from: 
            - dbdata
        expose:
            - "27017"
        depends_on:
            - dbdata
    build:
        container_name: log84-build
        build: ./build
        depends_on:
            - mongodb
            - server
        volumes:
            - ../:/var/lib/project/

    www: 
        container_name: log84-www
        image: nginx
        volumes: 
            - ./www/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../dist:/usr/share/nginx/html:ro
        links:
            - server
            - build
        depends_on:
            - server
            - build
        ports:
            - "8080:80"