version: '2'
services:
    node:
        container_name: log84-node
        build: ./node
        image: log84.de/node
        command: /bin/true
    redis:
        container_name: log84-redis
        build: ./redis
        image: log84.de/redis
        command: /bin/true
    redis-data:
        container_name: log84-redis-data
        image: log84.de/redis
        volumes:
            - /var/redis
        command: /bin/true
    redis-server:
        container_name: log84-redis-server
        build: ./redis-server
        volumes_from:
            - redis-data
        expose:
            - "6379"
        depends_on:
            - redis-data
    mongo-data:
        container_name: log84-mongo-data
        image: mongo
        volumes: 
            - /data/db
            - /data/configdb
        command: /bin/true      
    mongo-server:
        container_name: log84-mongo-server
        image: mongo
        volumes_from: 
            - mongo-data
        expose:
            - "27017"
        ports:
            - "27017:27017"
        depends_on:
            - mongo-data
    parse-server:
        container_name: log84-server
        build: ./parse-server
        env_file:
            - ./parse-server/env.properties
        expose:
            - "1337"
        links:
            - mongo-server
        depends_on:
            - node
            - mongo-server
    build:
        container_name: log84-build
        build: ./build
        depends_on:
            - mongo-server
            - parse-server
        volumes:
            - ../:/var/lib/project/:rw
    www:
        container_name: log84-www
        image: nginx
        volumes: 
            - ./www/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../dist:/usr/share/nginx/html:ro
        links:
            - parse-server
        depends_on:
            - parse-server
        ports:
            - "8080:80"